In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [10]:
a = np.empty([4, 2], dtype=np.uint16)
print(a.shape, a.ndim, a.itemsize)

(4, 2) 2 2


In [14]:
b = np.arange(100, 200, 10).reshape(5, 2)
print(b)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [46]:
sampleArray = np.array([[11, 22, 33], [44, 55, 66], [77, 88, 99]])
print(sampleArray)
print(sampleArray.take(2, axis=1))
print(sampleArray[::, 2])

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[33 66 99]
[33 66 99]


In [48]:
sampleArray = np.array([
	[3, 6, 9, 12],
	[15, 18, 21, 24],
	[27, 30, 33, 36],
	[39, 42, 45, 48],
	[51, 54, 57, 60],
])
print(sampleArray)
print(sampleArray[::2, 1::2])

[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]
[[ 6 12]
 [30 36]
 [54 60]]


In [58]:
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

res = arrayOne + arrayTwo
print(res)
print(res ** 2)

[[20 39 33]
 [25 25 28]]
[[ 400 1521 1089]
 [ 625  625  784]]


In [61]:
src = np.arange(10, 34, 1).reshape(8, 3)
print(src)
np.split(src, 4)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


[array([[10, 11, 12],
        [13, 14, 15]]),
 array([[16, 17, 18],
        [19, 20, 21]]),
 array([[22, 23, 24],
        [25, 26, 27]]),
 array([[28, 29, 30],
        [31, 32, 33]])]

In [91]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(sampleArray)

print("sort by second row")
print(sampleArray[:, sampleArray[1].argsort()])

print("sort by second column")
print(sampleArray[sampleArray[:, 1].argsort()])

[[34 43 73]
 [82 22 12]
 [53 94 66]]
sort by second row
[[73 43 34]
 [12 22 82]
 [66 94 53]]
sort by second column
[[82 22 12]
 [34 43 73]
 [53 94 66]]


In [95]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
print(np.amin(sampleArray, 1))
print(np.amax(sampleArray, 0))

[34 12 53]
[82 94 73]


In [100]:
sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = np.array([[10, 10, 10]])

newArray = np.delete(sampleArray, 1, 1)
print(newArray)
np.insert(newArray, 1, newColumn, axis=1)

[[34 73]
 [82 12]
 [53 66]]


array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])