## Numpy

In [1]:
import numpy as np

### Arrays & Matrices

Python list to Numpy array

In [2]:
np.array([10, 12, 14, 16, 20])

array([10, 12, 14, 16, 20])

2D matrix

In [3]:
np.array([[10, 12, 13], [14, 16, 18], [20, 22, 24]])

array([[10, 12, 13],
       [14, 16, 18],
       [20, 22, 24]])

Numpy array in range

In [4]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

One-filled array/matrix

In [5]:
np.ones([6, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Zero-filled array/matrix

In [6]:
np.zeros([6, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Identity matrix

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Decimal Random

In [8]:
np.random.rand(4, 5)

array([[0.89404539, 0.52369223, 0.50630895, 0.81688179, 0.75421274],
       [0.32404795, 0.76260174, 0.90508647, 0.7345218 , 0.87100878],
       [0.51935967, 0.65566626, 0.90424563, 0.26295571, 0.28193578],
       [0.18798002, 0.37255687, 0.26425081, 0.02372913, 0.58197254]])

Integer Random

In [9]:
np.random.randint(1, 100, 5)

array([ 9, 97, 52, 54, 16])

Matrix reshape

In [10]:
a = np.random.rand(4, 6)
print(a)

[[0.29805473 0.30953969 0.55816994 0.27623399 0.63826996 0.61778124]
 [0.39962504 0.8535156  0.62536651 0.10734814 0.24796466 0.21460793]
 [0.24765565 0.34561683 0.55820258 0.83160754 0.51179817 0.45520727]
 [0.34730957 0.25606682 0.33447965 0.27293055 0.5789844  0.29403412]]


In [11]:
a.reshape(6, 4)

array([[0.29805473, 0.30953969, 0.55816994, 0.27623399],
       [0.63826996, 0.61778124, 0.39962504, 0.8535156 ],
       [0.62536651, 0.10734814, 0.24796466, 0.21460793],
       [0.24765565, 0.34561683, 0.55820258, 0.83160754],
       [0.51179817, 0.45520727, 0.34730957, 0.25606682],
       [0.33447965, 0.27293055, 0.5789844 , 0.29403412]])

Array indexing/slicing

In [12]:
a = np.arange(1, 11)
print(a[1])
print(a[2:5])
print(a[:2])
print(a[2:])

2
[3 4 5]
[1 2]
[ 3  4  5  6  7  8  9 10]


Matrix indexing/slicing

In [13]:
_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(_2d[2,2])
print(_2d[:2,:])

9
[[1 2 3]
 [4 5 6]]


### Arithmetic Operations

Square roots

In [14]:
np.sqrt([10, 20, 30, 40, 50])

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

$$ln(x)$$

In [15]:
np.log([10, 20, 30, 40, 50])

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

$$e^x$$

In [16]:
np.exp([10, 20, 30, 40, 50])

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

$$sin(x)$$

In [17]:
np.sin([10, 20, 30, 40, 50])

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316, -0.26237485])

$$cos(x)$$

In [18]:
np.cos([10, 20, 30, 40, 50])

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806,  0.96496603])

### Linear Algebra Operations

Matrix Dot Product

In [19]:
a = np.random.randn(4, 5)
b = np.random.randn(5, 4)

print(a)
print(b)
np.dot(a, b)

[[-0.28823724  0.19899301  0.97206854  0.5548462   1.27367117]
 [-0.26822418  0.34977404 -0.90211106 -0.37627395 -1.87073853]
 [-2.00618017  0.23691748  0.84340481  0.34102791  0.26314589]
 [ 1.01604549 -1.20550883 -0.02230682 -0.01416063 -1.75907391]]
[[ 0.18258275 -0.79500851  2.34536496  0.48551667]
 [ 1.72619684  0.6169265   0.11786255  1.82776396]
 [-0.15537696 -1.47433486  2.2647305  -0.58141534]
 [-1.33234949  0.82466727 -0.15743738  1.14301403]
 [-0.22641652  0.9380499   0.75698617  0.78041339]]


array([[-0.88779235,  0.5710912 ,  2.4257035 ,  1.28677974],
       [ 1.61986752, -0.30610773, -3.98778038, -0.85645752],
       [-0.60232231,  1.02570839, -2.62170912, -0.43621092],
       [-1.47481689, -3.18036435,  0.86102901, -3.08609969]])

Element-wise Matrix Multiplication

In [20]:
matrix = np.array([[10, 2, 4], [3, 4, 5], [2, 2, 2]])
np.multiply(matrix, matrix)

array([[100,   4,  16],
       [  9,  16,  25],
       [  4,   4,   4]])

Matrix Inverse

In [21]:
matrix = np.array([[10, 2, 4], [3, 4, 5], [2, 2, 2]])
print(matrix)
np.linalg.inv(matrix)

[[10  2  4]
 [ 3  4  5]
 [ 2  2  2]]


array([[ 0.1, -0.2,  0.3],
       [-0.2, -0.6,  1.9],
       [ 0.1,  0.8, -1.7]])

Matrix Determinant

In [22]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(matrix)

0.0

Matrix Trace

In [23]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.trace(matrix)

15

Exercise 3.2

In [24]:
np.random.rand(5, 4)[2:,1:]

array([[7.06047167e-02, 5.85557541e-01, 3.04648725e-01],
       [9.05598096e-01, 9.79318747e-01, 8.66261761e-04],
       [1.81450512e-01, 5.81762837e-01, 7.32457415e-01]])