# Data Analysis

## Numpy

In [2]:
import numpy as np

### Arrays & Matrices

Python list to Numpy array

In [3]:
np.array([10, 12, 14, 16, 20])

array([10, 12, 14, 16, 20])

2D matrix

In [4]:
np.array([[10, 12, 13], [14, 16, 18], [20, 22, 24]])

array([[10, 12, 13],
       [14, 16, 18],
       [20, 22, 24]])

Numpy array in range

In [5]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

One-filled array/matrix

In [6]:
np.ones([6, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Zero-filled array/matrix

In [7]:
np.zeros([6, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Identity matrix

In [8]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Decimal Random

In [9]:
np.random.rand(4, 5)

array([[0.76504264, 0.10166477, 0.41581905, 0.25009587, 0.64807259],
       [0.061455  , 0.77641286, 0.09748582, 0.11426244, 0.40091699],
       [0.84407922, 0.29036872, 0.90213622, 0.19303459, 0.95668899],
       [0.37930711, 0.62970356, 0.56236052, 0.96013804, 0.19565866]])

Integer Random

In [10]:
np.random.randint(1, 100, 5)

array([36, 39, 25, 78, 40], dtype=int32)

Matrix reshape

In [11]:
a = np.random.rand(4, 6)
print(a)

[[0.42976162 0.50007227 0.32091182 0.76515994 0.46183883 0.83971467]
 [0.89043756 0.35982599 0.72009507 0.36264818 0.19615217 0.1534492 ]
 [0.65396607 0.02292659 0.8399793  0.18827874 0.86742581 0.48634522]
 [0.38597933 0.02238299 0.71506483 0.43490434 0.11014968 0.92046164]]


In [12]:
a.reshape(6, 4)

array([[0.42976162, 0.50007227, 0.32091182, 0.76515994],
       [0.46183883, 0.83971467, 0.89043756, 0.35982599],
       [0.72009507, 0.36264818, 0.19615217, 0.1534492 ],
       [0.65396607, 0.02292659, 0.8399793 , 0.18827874],
       [0.86742581, 0.48634522, 0.38597933, 0.02238299],
       [0.71506483, 0.43490434, 0.11014968, 0.92046164]])

Array indexing/slicing

In [13]:
a = np.arange(1, 11)
print(a[1])
print(a[2:5])
print(a[:2])
print(a[2:])

2
[3 4 5]
[1 2]
[ 3  4  5  6  7  8  9 10]


Matrix indexing/slicing

In [14]:
_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(_2d[2,2])
print(_2d[:2,:])

9
[[1 2 3]
 [4 5 6]]


### Arithmetic Operations

Square roots

In [15]:
np.sqrt([10, 20, 30, 40, 50])

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

$$ln(x)$$

In [16]:
np.log([10, 20, 30, 40, 50])

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301])

$$e^x$$

In [17]:
np.exp([10, 20, 30, 40, 50])

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21])

$$sin(x)$$

In [10]:
np.sin([10, 20, 30, 40, 50])

array([-5.44021111e-01,  9.12945251e-01, -9.88031624e-01,  7.45113160e-01,
        1.22464680e-16])

$$cos(x)$$

In [8]:
np.cos([10, 20, 30, 40, 50])

array([-0.83907153,  0.40808206,  0.15425145, -0.66693806, -1.        ])

### Linear Algebra Operations

Matrix Dot Product

In [26]:
a = np.random.randn(4, 5)
b = np.random.randn(5, 4)

print(a)
print(b)
np.dot(a, b)

[[-0.18569387  0.32855078 -1.01146882  0.2164486   2.26994004]
 [-0.15463811 -0.29214692 -0.7084402  -0.72351838 -1.25337869]
 [-1.69374797 -0.94788151 -0.34144435  1.21736526  1.69635322]
 [ 0.49228322 -0.80876081 -0.52844217  1.91648739  0.72767645]]
[[ 0.09437509  0.62882692  0.1131367   1.50646235]
 [ 1.75269722 -0.03892516 -1.44381557 -0.74660603]
 [ 0.58920298 -0.50676609 -1.19663738 -0.17626861]
 [ 1.06005835 -0.21357575 -2.13802205 -0.66935999]
 [-0.16234886  1.8374217  -0.13656292 -1.8836933 ]]


array([[-0.17670932,  4.50762881, -0.05777563, -4.76750149],
       [-1.50754126, -1.87531448,  2.97012036,  2.95531322],
       [-1.00729974,  2.00177105, -1.24888661, -5.79395236],
       [ 0.23103776,  1.53657193, -2.34111552, -1.21495964]])

Element-wise Matrix Multiplication

In [6]:
matrix = np.array([[10, 2, 4], [3, 4, 5], [2, 2, 2]])
np.multiply(matrix, matrix)

array([[100,   4,  16],
       [  9,  16,  25],
       [  4,   4,   4]])

Matrix Inverse

In [12]:
matrix = np.array([[10, 2, 4], [3, 4, 5], [2, 2, 2]])
print(matrix)
np.linalg.inv(matrix)

[[10  2  4]
 [ 3  4  5]
 [ 2  2  2]]


array([[ 0.1, -0.2,  0.3],
       [-0.2, -0.6,  1.9],
       [ 0.1,  0.8, -1.7]])

Matrix Determinant

In [14]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(matrix)

np.float64(6.66133814775094e-16)

Matrix Trace

In [18]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.trace(matrix)

np.int64(15)

Exercise 3.2

In [28]:
np.random.rand(5, 4)[2:,1:]

array([[0.90879874, 0.86678079, 0.57192638],
       [0.53043684, 0.52531363, 0.17455421],
       [0.44643946, 0.53070141, 0.25592176]])

## Pandas